package yawned;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;

import yawned.gui.DialogBox;

/**
 * Controls the main Yawned graphical user interface.
 */
public class MainWindow extends AnchorPane {
    @FXML
    private ScrollPane scrollPane;

    @FXML
    private VBox dialogContainer;

    @FXML
    private TextField userInput;

    @FXML
    private Button sendButton;

    private final Image userImage = new Image(getClass().getResourceAsStream("/images/DaUser.png"));
    private final Image yawnedImage = new Image(getClass().getResourceAsStream("/images/DaYawned.png"));
    private Yawned yawned;

    /**
     * Initializes the controls after FXML has injected them.
     */
    @FXML
    public void initialize() {
        scrollPane.vvalueProperty().bind(dialogContainer.heightProperty());
    }

    /**
     * Sets the chatbot that supplies responses to user messages.
     *
     * @param yawned Chatbot instance to use for responses.
     */
    public void setYawned(Yawned yawned) {
        this.yawned = yawned;
    }

    /**
     * Appends the user's input and Yawned's response to the dialog container.
     */
    @FXML
    private void handleUserInput() {
        String input = getUserInput();
        String response = getYawnedResponse(input);
        addDialogBoxes(input, response);
        clearUserInput();
    }

    /**
     * Returns the user's current input from the GUI.
     *
     * @return Current user input.
     */
    private String getUserInput() {
        return userInput.getText();
    }

    /**
     * Requests a response from the Yawned backend.
     *
     * @param input User input to send to Yawned.
     * @return Response generated by Yawned.
     */
    private String getYawnedResponse(String input) {
        return yawned.getResponse(input);
    }

    /**
     * Adds the user's message and Yawned's response to the dialog container.
     *
     * @param input User message to display.
     * @param response Yawned response to display.
     */
    private void addDialogBoxes(String input, String response) {
        dialogContainer.getChildren().addAll(
                DialogBox.getUserDialog(input, userImage),
                DialogBox.getYawnedDialog(response, yawnedImage));
    }

    /**
     * Clears the text field after the current message is handled.
     */
    private void clearUserInput() {
        userInput.clear();
    }
}
